name: Godot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  EXPORT_NAME: test-project

jobs:
  import-assets:
    runs-on: ubuntu-latest
    container: 
      image: barichello/godot-ci:4.0.2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Import Assets
      run: godot -v -e --quit --headless

  export:
    needs: import-assets
    runs-on: ubuntu-latest
    container: 
      image: barichello/godot-ci:4.0.2
    strategy:
      matrix:
        platform: ["Linux/X11", "Windows Desktop", "Mac OSX", "HTML5", "Android Debug", "Android"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Export
      run: |
        mkdir -v -p build/${{ matrix.platform }}
        cd $EXPORT_NAME
        godot -v --export-release --headless "${{ matrix.platform }}" ../build/${{ matrix.platform }}/$EXPORT_NAME.${{ matrix.platform == 'Linux/X11' && 'x86_64' || matrix.platform == 'Windows Desktop' && 'exe' || matrix.platform == 'Mac OSX' && 'zip' || matrix.platform == 'HTML5' && 'index.html' || matrix.platform == 'Android Debug' && 'apk' || 'apk' }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.EXPORT_NAME }}-${{ matrix.platform }}
        path: build/${{ matrix.platform }}

  deploy:
    needs: export
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.EXPORT_NAME }}-HTML5
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/HTML5
